apiVersion: 1

datasources:
  - name: GROUNDCOVER-PROMETHEUS
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 5s
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: false
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 5s
